/*
 * nq-conv — sprite-sheet → NqAtlas C header generator.
 *
 * Usage:
 *   nq-conv <output.h> <atlas_name> <cols> <rows> [tex_w] [tex_h]
 *
 * Generates NQ_ATLAS_<name>_WIDTH / _HEIGHT (defaults 0/0 → caller's job)
 * and one NqRect constant per cell, named by 0-based index:
 *
 *   NQ_ATLAS_<name>_REGION_<i>_X / _Y / _W / _H
 *
 * The output is a pure-C header; no runtime dependency on nq_core.
 * Pair with nq_atlas to declare named regions in code, OR inline the
 * NqRect values into NqAtlas calls. Either way, the asset pipeline
 * produces a checked-in source file rather than runtime metadata.
 *
 * Example:
 *   nq-conv assets/player.h PLAYER 8 8 1024 1024
 *     → assets/player.h with NQ_ATLAS_PLAYER_REGION_{0..63}_*
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define LINE_BUF_SIZE 512

static void sanitize_ident(char *dst, size_t dst_cap, const char *src) {
    /* Make src into a valid C identifier suffix. Rules:
     * - alphanumeric + underscore only
     * - must start with letter or underscore (otherwise prefix with '_')
     * - uppercase as a convention since the generated names go before uppercase tags */
    size_t j = 0;
    int need_underscore_prefix = 1;
    for (size_t i = 0; src[i] && j + 1 < dst_cap; i++) {
        char c = src[i];
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '_') {
            if (need_underscore_prefix && c >= '0' && c <= '9') {
                dst[j++] = '_';
            }
            if (c >= 'a' && c <= 'z') c = (char)(c - 'a' + 'A');
            dst[j++] = c;
            need_underscore_prefix = 0;
        } else {
            dst[j++] = '_';
            need_underscore_prefix = 0;
        }
    }
    dst[j] = '\0';
}

static void emit_header(FILE *out,
                       const char *atlas_name,
                       int cols, int rows,
                       int tex_w, int tex_h) {
    char safe[128];
    sanitize_ident(safe, sizeof(safe), atlas_name);

    fprintf(out, "/* Auto-generated by tools/nq-conv. Do not edit. */\n");
    fprintf(out, "#ifndef NQ_ATLAS_%s_H\n", safe);
    fprintf(out, "#define NQ_ATLAS_%s_H\n", safe);
    fprintf(out, "\n");
    fprintf(out, "/* Sheet dimensions in pixels — caller is responsible for\n");
    fprintf(out, " * knowing the underlying texture size. 0 means \"unspecified\". */\n");
    fprintf(out, "#define NQ_ATLAS_%s_TEX_W %d\n", safe, tex_w);
    fprintf(out, "#define NQ_ATLAS_%s_TEX_H %d\n", safe, tex_h);
    fprintf(out, "#define NQ_ATLAS_%s_COLS %d\n", safe, cols);
    fprintf(out, "#define NQ_ATLAS_%s_ROWS %d\n", safe, rows);
    fprintf(out, "\n");
    fprintf(out, "/* Per-cell rectangles. Use NqRect r = nq_rect(\n");
    fprintf(out, " *     NQ_ATLAS_<name>_REGION_<i>_X,\n");
    fprintf(out, " *     NQ_ATLAS_<name>_REGION_<i>_Y,\n");
    fprintf(out, " *     NQ_ATLAS_<name>_REGION_<i>_W,\n");
    fprintf(out, " *     NQ_ATLAS_<name>_REGION_<i>_H);\n");
    fprintf(out, " * or wire them into nq_atlas_add_region at startup. */\n");
    if (tex_w > 0 && tex_h > 0 && cols > 0 && rows > 0) {
        int cell_w = tex_w / cols;
        int cell_h = tex_h / rows;
        fprintf(out, "\n");
        fprintf(out, "/* Pre-computed region rectangles (origin (0,0), uniform grid): */\n");
        for (int j = 0; j < rows; j++) {
            for (int i = 0; i < cols; i++) {
                int idx = j * cols + i;
                fprintf(out, "#define NQ_ATLAS_%s_REGION_%d_X %d\n",
                        safe, idx, i * cell_w);
                fprintf(out, "#define NQ_ATLAS_%s_REGION_%d_Y %d\n",
                        safe, idx, j * cell_h);
                fprintf(out, "#define NQ_ATLAS_%s_REGION_%d_W %d\n",
                        safe, idx, cell_w);
                fprintf(out, "#define NQ_ATLAS_%s_REGION_%d_H %d\n",
                        safe, idx, cell_h);
            }
        }
    }
    fprintf(out, "\n#endif /* NQ_ATLAS_%s_H */\n", safe);
}

static int parse_int(const char *s, int *out) {
    if (!s || !*s) return 0;
    char *end = NULL;
    long v = strtol(s, &end, 10);
    if (end == s || *end != '\0' || v < 1 || v > 1000000) return 0;
    *out = (int)v;
    return 1;
}

static void usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s <output.h> <atlas_name> <cols> <rows> [tex_w] [tex_h]\n"
        "  Generates C-header constants for an NqAtlas from a uniform grid.\n"
        "  Without tex_w/tex_h only the count macros are emitted.\n",
        prog);
}

int main(int argc, char **argv) {
    if (argc < 5) {
        usage(argv[0]);
        return 1;
    }
    const char *out_path = argv[1];
    const char *atlas_name = argv[2];
    int cols, rows, tex_w = 0, tex_h = 0;
    if (!parse_int(argv[3], &cols)) {
        fprintf(stderr, "nq-conv: cols must be a positive integer\n");
        return 1;
    }
    if (!parse_int(argv[4], &rows)) {
        fprintf(stderr, "nq-conv: rows must be a positive integer\n");
        return 1;
    }
    if (argc > 5 && !parse_int(argv[5], &tex_w)) {
        fprintf(stderr, "nq-conv: tex_w must be a positive integer\n");
        return 1;
    }
    if (argc > 6 && !parse_int(argv[6], &tex_h)) {
        fprintf(stderr, "nq-conv: tex_h must be a positive integer\n");
        return 1;
    }
    if (tex_w > 0 && tex_h == 0) tex_h = tex_w;  /* square cell fallback */
    if (tex_h > 0 && tex_w == 0) tex_w = tex_h;

    FILE *out = fopen(out_path, "w");
    if (!out) {
        fprintf(stderr, "nq-conv: cannot open %s for writing\n", out_path);
        return 1;
    }
    emit_header(out, atlas_name, cols, rows, tex_w, tex_h);
    fclose(out);
    return 0;
}
