name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - name: Install dependencies
      run: bash .github/scripts/install-sdl3-ubuntu.sh
        
    - name: Configure CMake
      run: cmake -B build -S . -DNQ_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build build
      
    - name: Test
      working-directory: build
      run: ctest --output-on-failure
